image: Visual Studio 2017

version: '{build}'

install:
  - cinst fake -pre
  - cinst paket

build_script:
  - cmd: build.bat

test: off
  
artifacts:
  - path: Src\deploy

environment:
  TSD_GITHUB_TOKEN:
    secure: aomLg/UJoANZHNObs3xgs6lt6+LoiUtpiO9pUV4mXsRJYuWD3VvNPLQsd/hcocEf